const NOTFOUND = 404;
const SERVERERROR = 500;
const SUCCESS = 200;
const EMAILORPASSWORDINVAID = 401;
const VALIDATION = 406;
const EXIST = 403;

module.exports = {
  NOTFOUND,
  SERVERERROR,
  SUCCESS,
  VALIDATION,
  EMAILORPASSWORDINVAID,
  EXIST,
};
